# numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

# 1 dimensional Array

[1, 2, 3]

In [3]:
a = np.array( [1,2,3] )

In [4]:
a

array([1, 2, 3])

In [5]:
type( a )

numpy.ndarray

In [10]:
a.shape

(3,)

In [28]:
(3,)

(3,)

In [11]:
a.ndim

1

In [12]:
len(a)

3

# 2 dimensional Array

[[1,2,3]

 [2,3,4]]

In [6]:
B = np.array( [[1,2,3], [2,3,4]] )

In [7]:
B.ndim

2

In [8]:
B.itemsize

8

In [16]:
B.dtype

dtype('int64')

In [12]:
type( B )

numpy.ndarray

In [17]:
B.shape

(2, 3)

In [14]:
len(B)

2

In [14]:
B

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
B[ 1][2 ]

4

In [12]:
B[ 0,1 ]

2

In [22]:
B

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
C = np.array( [[ 3,6, 9 ]] )

In [14]:
C

array([[3, 6, 9]])

In [15]:
C.ndim

2

In [16]:
C.shape

(1, 3)

In [17]:
D = np.array( [ [ 5 ], [ 10 ] ] )

In [19]:
D

array([[ 5],
       [10]])

In [20]:
B

array([[1, 2, 3],
       [2, 3, 4]])

In [26]:
np.concatenate( ( B, D ), axis = 1 )

array([[ 1,  2,  3,  5],
       [ 2,  3,  4, 10]])

In [27]:
np.concatenate( ( B, C ), axis = 0 )

array([[1, 2, 3],
       [2, 3, 4],
       [3, 6, 9]])

In [28]:
np.append( B, C )

array([1, 2, 3, 2, 3, 4, 3, 6, 9])

In [29]:
np.insert( B, 2, [10, 7], axis = 1 )

array([[ 1,  2, 10,  3],
       [ 2,  3,  7,  4]])

In [30]:
np.insert( B, 1, [3,9, 9], axis = 0 )

array([[1, 2, 3],
       [3, 9, 9],
       [2, 3, 4]])

In [31]:
np.insert( B, 1, [3], axis = 1 )

array([[1, 3, 2, 3],
       [2, 3, 3, 4]])

In [33]:
C = np.insert( B, 1, [3], axis = 0 )

In [34]:
C

array([[1, 2, 3],
       [3, 3, 3],
       [2, 3, 4]])

In [35]:
C + 6.3

array([[ 7.3,  8.3,  9.3],
       [ 9.3,  9.3,  9.3],
       [ 8.3,  9.3, 10.3]])

In [36]:
C - C

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [37]:
C - 6

array([[-5, -4, -3],
       [-3, -3, -3],
       [-4, -3, -2]])

# Array Multiplication

In [38]:
A = np.insert( B, 1, [3,3,9], axis = 0 )

In [39]:
A

array([[1, 2, 3],
       [3, 3, 9],
       [2, 3, 4]])

In [40]:
C

array([[1, 2, 3],
       [3, 3, 3],
       [2, 3, 4]])

In [41]:
A*C

array([[ 1,  4,  9],
       [ 9,  9, 27],
       [ 4,  9, 16]])

In [47]:
np.ones( ( 3,3 )  )

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
A

array([[1, 2, 3],
       [3, 3, 9],
       [2, 3, 4]])

In [42]:
A.dot(np.ones( ( 3,3 )  ))

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [ 9.,  9.,  9.]])

In [43]:
A@np.ones( ( 3,3 )  )

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [ 9.,  9.,  9.]])

In [48]:
np.dot( A, C )

array([[13, 17, 21],
       [30, 42, 54],
       [19, 25, 31]])

In [45]:
A.dot(C)

array([[13, 17, 21],
       [30, 42, 54],
       [19, 25, 31]])

In [46]:
A@C

array([[13, 17, 21],
       [30, 42, 54],
       [19, 25, 31]])

In [36]:
A

array([[1, 2, 3],
       [3, 3, 9],
       [2, 3, 4]])

# Matrix Inverse

In [49]:
A

array([[1, 2, 3],
       [3, 3, 9],
       [2, 3, 4]])

In [50]:
A_inv = np.linalg.inv( A )

In [51]:
A_inv

array([[-2.5       ,  0.16666667,  1.5       ],
       [ 1.        , -0.33333333,  0.        ],
       [ 0.5       ,  0.16666667, -0.5       ]])

In [52]:
A_inv.dot(A)

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.55111512e-17, 1.00000000e+00, 1.66533454e-16],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [53]:
np.identity( 3 )

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Multi-Dimension

In [54]:
C = np.array([ [ [1,2], [1,2] ], [ [1,2] ,[1,2] ] ])

In [55]:
C.shape

(2, 2, 2)

In [56]:
C.ndim

3

# Mean and STD

In [57]:
import numpy as np

In [58]:
input_000568 = [279.18, 279.00, 279.06, 287.79, 290.50, 298.10, 313.99, 292.40]
input_000858 = [304.12, 308.75, 313.60, 319.76, 320.00, 329.50, 342.65, 333.50]

In [59]:
arrays = np.array([ input_000568, input_000858 ])

In [60]:
arrays

array([[279.18, 279.  , 279.06, 287.79, 290.5 , 298.1 , 313.99, 292.4 ],
       [304.12, 308.75, 313.6 , 319.76, 320.  , 329.5 , 342.65, 333.5 ]])

In [61]:
arrays.shape

(2, 8)

In [62]:
arrays.mean()

305.74375

In [63]:
arrays.mean( axis = 1 )

array([290.0025, 321.485 ])

In [64]:
arrays.mean( axis = 0 )

array([291.65 , 293.875, 296.33 , 303.775, 305.25 , 313.8  , 328.32 ,
       312.95 ])

In [65]:
arrays[ 1:2, 2:5 ] # 2 - dim

array([[313.6 , 319.76, 320.  ]])

In [66]:
arrays[ 1, 2:5 ] # 1 - dim

array([313.6 , 319.76, 320.  ])

In [67]:
arrays

array([[279.18, 279.  , 279.06, 287.79, 290.5 , 298.1 , 313.99, 292.4 ],
       [304.12, 308.75, 313.6 , 319.76, 320.  , 329.5 , 342.65, 333.5 ]])

# Relative Return

In [68]:
rel_ret = arrays[ :, 1: ]/arrays[ :, :-1 ]-1

In [54]:
rel_ret

array([[-0.00064475,  0.00021505,  0.03128359,  0.00941659,  0.02616179,
         0.05330426, -0.06876015],
       [ 0.01522425,  0.0157085 ,  0.01964286,  0.00075056,  0.0296875 ,
         0.03990895, -0.02670363]])

In [55]:
arrays[ :, 1: ]

array([[279.  , 279.06, 287.79, 290.5 , 298.1 , 313.99, 292.4 ],
       [308.75, 313.6 , 319.76, 320.  , 329.5 , 342.65, 333.5 ]])

In [56]:
arrays[ :, :-1 ]

array([[279.18, 279.  , 279.06, 287.79, 290.5 , 298.1 , 313.99],
       [304.12, 308.75, 313.6 , 319.76, 320.  , 329.5 , 342.65]])

# In class practice: calculate absolute return

In [69]:
arrays[ :, 1: ] - arrays[ :, :-1 ]

array([[ -0.18,   0.06,   8.73,   2.71,   7.6 ,  15.89, -21.59],
       [  4.63,   4.85,   6.16,   0.24,   9.5 ,  13.15,  -9.15]])

# In class practice: calculate log return

In [70]:
np.log( arrays[ :, 1: ]/arrays[ :, :-1 ] )

array([[-0.00064495,  0.00021503,  0.03080424,  0.00937253,  0.02582542,
         0.05193214, -0.07123841],
       [ 0.01510953,  0.0155864 ,  0.01945243,  0.00075028,  0.02925536,
         0.03913316, -0.02706665]])

In [71]:
import math

In [72]:
math.log(2)

0.6931471805599453

In [73]:
arrays[ :, :-1 ]

array([[279.18, 279.  , 279.06, 287.79, 290.5 , 298.1 , 313.99],
       [304.12, 308.75, 313.6 , 319.76, 320.  , 329.5 , 342.65]])

In [75]:
np.log( arrays[ :, 1: ]) - np.log( arrays[ :, :-1 ] )

array([[-0.00064495,  0.00021503,  0.03080424,  0.00937253,  0.02582542,
         0.05193214, -0.07123841],
       [ 0.01510953,  0.0155864 ,  0.01945243,  0.00075028,  0.02925536,
         0.03913316, -0.02706665]])

In [77]:
log_ret = np.log( arrays[ :, 1: ]/arrays[ :, :-1 ] )

In [78]:
log_ret

array([[-0.00064495,  0.00021503,  0.03080424,  0.00937253,  0.02582542,
         0.05193214, -0.07123841],
       [ 0.01510953,  0.0155864 ,  0.01945243,  0.00075028,  0.02925536,
         0.03913316, -0.02706665]])

# Covariance and variance

In [79]:
log_ret.std( axis = 1 )

array([0.03619437, 0.01983911])

In [85]:
np.std( log_ret, axis = 1 )

array([0.03619437, 0.01983911])

In [82]:
np.cov(log_ret)

array([[0.00152837, 0.00078439],
       [0.00078439, 0.00045919]])

In [86]:
log_ret.var( axis = 1, ddof = 1 )

array([0.00152837, 0.00045919])

In [88]:
log_ret.var( axis = 1, ddof = 0 )

array([0.00131003, 0.00039359])

In [87]:
np.power( log_ret.std( axis = 1 ), 2 )

array([0.00131003, 0.00039359])

In [24]:
np.var( log_ret, axis = 1 ) 

array([0.00131003, 0.00039359])

In [26]:
#np.var( log_ret, axis = 1 ) * (arrays.shape[1]-1) / ( arrays.shape[1]-2 )

In [26]:
np.cov(log_ret, ddof = 1 )

array([[0.00152837, 0.00078439],
       [0.00078439, 0.00045919]])

# In class practice: Calculate Covariance Matrix Step by Step

$X$ is a $k$ by $N$ matrix, then the covariance matrix of $X$ is calculated as:
$(X-\mu)(X-\mu)^T/(N-1)$

In [64]:
log_ret.mean(axis = 1)

array([0.00660943, 0.01317436])

In [68]:
log_ret.mean(axis = 1, keepdims = True)

array([[0.00660943],
       [0.01317436]])

In [69]:
#log_ret.mean(axis = 1, keepdims = True).T

In [70]:
#arrays

In [89]:
log_ret

array([[-0.00064495,  0.00021503,  0.03080424,  0.00937253,  0.02582542,
         0.05193214, -0.07123841],
       [ 0.01510953,  0.0155864 ,  0.01945243,  0.00075028,  0.02925536,
         0.03913316, -0.02706665]])

In [92]:
log_ret_demean = log_ret - log_ret.mean(axis = 1, keepdims = True)

In [93]:
#log_ret_demean

In [94]:
#log_ret_demean.shape

In [95]:
log_ret_demean.dot( log_ret_demean.T ) / ( log_ret_demean.shape[1] -1 )

array([[0.00152837, 0.00078439],
       [0.00078439, 0.00045919]])

In [78]:
log_ret_demean.dot( log_ret_demean.T ) / ( log_ret_demean.shape[1] )

array([[0.00131003, 0.00067233],
       [0.00067233, 0.00039359]])

In [79]:
np.cov( log_ret )

array([[0.00152837, 0.00078439],
       [0.00078439, 0.00045919]])

In [80]:
#np.cov?

# In Class Practice Linear Regression

$Y = X\beta$

$\beta =  (X^TX)^{-1}X^TY$ 

In [96]:
np.random.seed(5)

In [97]:
sample_inputarray = np.random.rand( 3,20 ) #[0,1)

In [98]:
sample_inputarray

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
        0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123,
        0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703,
        0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781],
       [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395,
        0.1441643 , 0.16561286, 0.96393053, 0.96022672, 0.18841466,
        0.02430656, 0.20455555, 0.69984361, 0.77951459, 0.02293309,
        0.57766286, 0.00164217, 0.51547261, 0.63979518, 0.9856244 ],
       [0.2590976 , 0.80249689, 0.87048309, 0.92274961, 0.00221421,
        0.46948837, 0.98146874, 0.3989448 , 0.81373248, 0.5464565 ,
        0.77085409, 0.48493107, 0.02911156, 0.08652569, 0.11145381,
        0.25124511, 0.96491529, 0.63176605, 0.8166602 , 0.566082  ]])

In [99]:
sample_inputarray[0, :]

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
       0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123,
       0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703,
       0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781])

In [100]:
sample_inputarray[1:, :]

array([[0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395,
        0.1441643 , 0.16561286, 0.96393053, 0.96022672, 0.18841466,
        0.02430656, 0.20455555, 0.69984361, 0.77951459, 0.02293309,
        0.57766286, 0.00164217, 0.51547261, 0.63979518, 0.9856244 ],
       [0.2590976 , 0.80249689, 0.87048309, 0.92274961, 0.00221421,
        0.46948837, 0.98146874, 0.3989448 , 0.81373248, 0.5464565 ,
        0.77085409, 0.48493107, 0.02911156, 0.08652569, 0.11145381,
        0.25124511, 0.96491529, 0.63176605, 0.8166602 , 0.566082  ]])

In [102]:
YT = sample_inputarray[0, :]

In [103]:
XT = np.insert( sample_inputarray[1:, :], 0, 1, axis = 0 )

In [104]:
YT

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
       0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123,
       0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703,
       0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781])

In [106]:
XT

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395,
        0.1441643 , 0.16561286, 0.96393053, 0.96022672, 0.18841466,
        0.02430656, 0.20455555, 0.69984361, 0.77951459, 0.02293309,
        0.57766286, 0.00164217, 0.51547261, 0.63979518, 0.9856244 ],
       [0.2590976 , 0.80249689, 0.87048309, 0.92274961, 0.00221421,
        0.46948837, 0.98146874, 0.3989448 , 0.81373248, 0.5464565 ,
        0.77085409, 0.48493107, 0.02911156, 0.08652569, 0.11145381,
        0.25124511, 0.96491529, 0.63176605, 0.8166602 , 0.566082  ]])

In [110]:
np.linalg.inv( XT.dot( XT.T ) ).dot( XT.dot(YT.T) )

array([ 0.5059354 , -0.16500893,  0.08163346])

# Verification

In [108]:
np.linalg.lstsq( XT.T, YT.T )[0]

<ipython-input-108-58d56e3120ae>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq( XT.T, YT.T )[0]


array([ 0.5059354 , -0.16500893,  0.08163346])